DROP TABLE IF EXISTS meals CASCADE;

CREATE TABLE meals (
  id SERIAL PRIMARY KEY NOT NULL,
  restaurant_id INTEGER REFERENCES restaurants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  photo_url VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  time_to_cook INTEGER NOT NULL,
  availible BOOLEAN NOT NULL DEFAULT TRUE
);
